### ISSUE TITLE
Data validation

### ISSUE THREAD

**Issue by joelharkes** [JanBurp/ToGo#2]
Misschien ben ik nog te snel maar ik mis nog enige backend validatie bijvoorbeeld hier:

https://github.com/JanBurp/ToGo/blob/51bd5a4eb6a594ae7656cba7f3ce4c1f05082fe5/app/Http/Controllers/LocationsController.php#L66-L71

alsje bijv de api call doet:
fetch("http://localhost/api/locations/3", {
  "headers": {
    "content-type": "application/json",
  "referrer": "http://localhost/",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"visited\":\"testsadfasf\"}",
  "method": "PATCH",
  "mode": "cors",
  "credentials": "include"
});

krijg je een server 500 db server error.

Waarom zit hier geen validatie op?

**Comment by JanBurp** [comment]
Goed punt, en inderdaad was ik nog niet aantoe gekomen, bij deze ;-)
