### ISSUE TITLE
Async functions?

### ISSUE THREAD

**Issue by joelharkes** [JanBurp/ToGo#5]
https://github.com/JanBurp/ToGo/blob/034881d8f8df9cb4c6695cf9359ffb8f46657b5c/resources/js/Togo/TogoHome.vue#L102-L124

why have you not used async and await?

```js
try {
  response = await axios(...);
  return data
}
catch(error) {
   /// all error handling
  // you could also nicely show error using the CompositionApi?
}
```

**Comment by JanBurp** [comment]
solved ;-)
